spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: postgres
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  profiles:
    active:
